### ISSUE TITLE
PgStac no longer works with Azure Flexible Postgres server

### ISSUE THREAD

**Issue by martys** [stac-utils/stac-fastapi-pgstac#65]
A few days ago Microsoft has bumped up a minor version of a "Azure Database for PostgreSQL flexible server" to version 13.12

After that all PGStac methods using that are utilized by Stac-Fast-Api stopped working !
resulting in a "segmentation fault" and not returning any data back.

Executing the same queries or stored procedures using a PGAdmin works fine, indicating a problem with pgstab library

We are in the middle of production outage right now due to this, and will add more details as they become available.

**Comment by gadomski** [comment]
cc @bitner ☝🏼

**Comment by martys** [comment]
here are some more detailed log's from our code
```

Traceback (most recent call last):

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/pool.py", line 218, in release

    self._con.terminate()

AttributeError: 'NoneType' object has no attribute 'terminate'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi

    result = await app(self.scope, self.receive, self.send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__

    return await self.app(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__

    await super().__call__(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__

    raise exc

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__

    await self.app(scope, receive, _send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/stac_fastapi/api/middleware.py", line 76, in __call__

    await self.app(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__

    await self.app(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/brotli_asgi/__init__.py", line 81, in __call__

    await br_responder(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/brotli_asgi/__init__.py", line 126, in __call__

    await self.app(scope, receive, self.send_with_brotli)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__

    raise exc

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__

    await self.app(scope, receive, sender)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__

    await route.handle(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle

    await self.app(scope, receive, send)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/starlette/routing.py", line 61, in app

    response = await func(request)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app

    raw_response = await run_endpoint_function(

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function

    return await dependant.call(**values)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/stac_fastapi/api/routes.py", line 57, in _endpoint

    await func(request=request, **request_data.kwargs()), response_class

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/stac_fastapi/pgstac/core.py", line 42, in all_collections

    async with pool.acquire() as conn:

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/pool.py", line 1012, in __aexit__

    await self.pool.release(con)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/pool.py", line 886, in release

    return await asyncio.shield(ch.release(timeout))

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/pool.py", line 220, in release

    raise ex

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/pool.py", line 210, in release

    await self._con.reset(timeout=budget)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1366, in reset

    await self.execute(reset_query, timeout=timeout)

  File "/home/mantasmantas/projects/Atlas-Platform/app/atlas_ui/stac_fastapi/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 317, in execute

    return await self._protocol.query(query, timeout)

  File "asyncpg/protocol/protocol.pyx", line 338, in query

asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation
 like 1
```

**Comment by martys** [comment]
same issue with v14 or v15 as well

**Comment by bitner** [comment]
@martys the error messages you are receiving do not look like it is a Postgres version issue, it looks like there is an issue with getting your connection using asyncpg. Can you confirm that you can use the asyncpg library to make a connection from the machine you are running stac_fastapi on to your database?

**Comment by martys** [comment]
@bitner  - no we don't recall doing any changes. Just noticed that Azure has executed and upgrade from 13.11 to 13.12 

We've deployed a 13.12 server locally and the code works - so this might be azure specific. Just not sure how to get to the bottom of the issue.

**Comment by mmcfarland** [comment]
Just as an additional datapoint, we are running pgstac 0.7.5 on Azure Postgres Flexible Server with PostgreSQL 14.8 and haven't noticed any connectivity issues.

**Comment by bitner** [comment]
@martys I would definitely start by just try connecting to your Azure Flex Server using asyncpg and just running any query ie `SELECT 1;` from the server you are running stac-fastapi on. Perhaps they updated a certificate or something for SSL?

**Comment by martys** [comment]
`SELECT 1;` works

**Comment by bitner** [comment]
That error still looks like it is related to the database connection - I don't see any evidence in that traceback that indicates that indicates that any pgstac queries have even made it to the database. That error is coming from the asyncpg library, but is not indicating any kind of bad query - it is indicating some kind of issue with your connection.

When you tried `SELECT 1;` did you run that using asyncpg with the same connection parameters from the same server that you are having problems on with stac-fastapi-pgstac?

**Comment by martys** [comment]
we're suspecting the connection pooling at this point, but still working to reproduce exactly

**Comment by kneitukas** [comment]
> That error still looks like it is related to the database connection - I don't see any evidence in that traceback that indicates that indicates that any pgstac queries have even made it to the database. That error is coming from the asyncpg library, but is not indicating any kind of bad query - it is indicating some kind of issue with your connection.
> 
> When you tried `SELECT 1;` did you run that using asyncpg with the same connection parameters from the same server that you are having problems on with stac-fastapi-pgstac?

Connections are established, here is some more context:

```

{"processId": 1,"errorLevel": "DEBUG", "message": "forked new backend, pid=18442 socket=10"}
{"processId": 18442,"errorLevel": "LOG", "message": "connection received: host=<redacted> port=4097"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: handshake start: \"before SSL initialization\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"before SSL initialization\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept exit (-1): \"before SSL initialization\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"before SSL initialization\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS read client hello\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write server hello\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write change cipher spec\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"TLSv1.3 early data\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept exit (-1): \"TLSv1.3 early data\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"TLSv1.3 early data\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS read client hello\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write server hello\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"TLSv1.3 write encrypted extensions\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write certificate request\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write certificate\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"TLSv1.3 write server certificate verify\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write finished\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"TLSv1.3 early data\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept exit (-1): \"TLSv1.3 early data\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"TLSv1.3 early data\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS read client certificate\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS read finished\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: handshake done: \"SSLv3/TLS write session ticket\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: handshake start: \"SSLv3/TLS write session ticket\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write session ticket\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: handshake done: \"SSLv3/TLS write session ticket\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: handshake start: \"SSLv3/TLS write session ticket\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept loop: \"SSLv3/TLS write session ticket\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: handshake done: \"SSL negotiation finished successfully\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL: accept exit (1): \"SSL negotiation finished successfully\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "SSL connection from DN:\"(anonymous)\" CN:\"(anonymous)\""}
{"processId": 18442,"errorLevel": "DEBUG", "message": "InitPostgres"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "my backend ID is 9"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "received password packet"}
{"processId": 18442,"errorLevel": "LOG", "message": "connection authenticated: identity=\"<redacted>\" method=md5 (/datadrive/pg/data/pg_hba.conf:25)"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Executing azure_preauth function..."}
{"processId": 18442,"errorLevel": "DEBUG", "message": "connections_succeeded metric was successfully sent."}
{"processId": 18442,"errorLevel": "LOG", "message": "connection authorized: user=<redacted> database=postgres application_name=pgstac SSL enabled (protocol=TLSv1.3, cipher=TLS_AES_256_GCM_SHA384, bits=256)"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "parse __asyncpg_stmt_30__: SELECT\n    t.oid,\n    t.typelem     AS elemtype,\n    t.typtype     AS kind\nFROM\n    pg_catalog.pg_type AS t\nWHERE\n    t.oid = $1\n"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 85"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "bind <unnamed> to __asyncpg_stmt_30__"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "parse __asyncpg_stmt_31__: SELECT\n    t.oid,\n    t.typelem     AS elemtype,\n    t.typtype     AS kind\nFROM\n    pg_catalog.pg_type AS t\nWHERE\n    t.oid = $1\n"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 85"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "bind <unnamed> to __asyncpg_stmt_31__"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "parse __asyncpg_stmt_32__: \n                SELECT * FROM all_collections();\n                "}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "bind <unnamed> to __asyncpg_stmt_32__"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 38","query": "\n\n    SELECT jsonb_agg(content) FROM collections;\n\n;\n\n","context": "SQL function \"all_collections\" during startup"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 38","query": "\n\n    SELECT jsonb_agg(content) FROM collections;\n\n;\n\n","context": "SQL function \"all_collections\" during startup"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 38","query": "\n\n    SELECT jsonb_agg(content) FROM collections;\n\n;\n\n","context": "SQL function \"all_collections\" during startup"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0","context": "SQL function \"all_collections\" statement 1"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0","context": "SQL function \"all_collections\" statement 1"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0","context": "SQL function \"all_collections\" statement 1"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0","context": "SQL function \"all_collections\" statement 1"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0","context": "SQL function \"all_collections\" statement 1"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 8"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 8"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0 at character 8"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 18442,"errorLevel": "DEBUG", "message": "Security context:0"}
{"processId": 1,"errorLevel": "DEBUG", "message": "reaping dead processes"}
{"processId": 1,"errorLevel": "DEBUG", "message": "server process (PID 18442) was terminated by signal 11: Segmentation fault","detail": "Failed process was running: SELECT pg_advisory_unlock_all();\nCLOSE ALL;\nUNLISTEN *;\nRESET ALL;"}
{"processId": 1,"errorLevel": "LOG", "message": "terminating any other active server processes"}

```

**Comment by bitner** [comment]
@martys I have no idea how to help you with this. I have no capability to reproduce this.

**Comment by martys** [comment]
here's a sample project - with a public database in the cloud made available that easily reproduces the issue, 
which seems to happen after the data is read from the DB and the connection is being disposed 


![image](https://github.com/stac-utils/stac-fastapi-pgstac/assets/210054/3d1fa854-4b65-4f0d-be02-f08b3e539240)


```
import asyncio
from stac_fastapi.pgstac.db import DB
from stac_fastapi.pgstac.config import Settings

def create_db():

    db = DB()
    settings = Settings(
        postgres_dbname = 'postgres',
        postgres_user = 'demoadmin',
        postgres_pass = 'vPf3BtYM1WzvbAJ',
        postgres_host_reader = 'testpgstac.postgres.database.azure.com',
        postgres_host_writer = 'testpgstac.postgres.database.azure.com',
        postgres_port = '5432'
    )
    return db,settings


async def run():
    
    db, settings = create_db()
    
    readpool = settings.reader_connection_string
    pool = await db.create_pool(readpool, settings)
    
    async with pool.acquire() as conn:
        collections = await conn.fetchval(
            """
            SELECT * FROM all_collections();
            """
        )
        print(collections)
    
    print("Done")

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

**Comment by gadomski** [comment]
Closing as can't reproduce.

**Comment by martys** [comment]
Issue resolved from Microsoft side. 
Thanks to everyone involved!
